### ISSUE TITLE
Sidebar cant be closed in mobile view.

### ISSUE THREAD

**Issue by appelskrutt34** [SveltePress/sveltepress#117]
### Describe the bug

After creating a project with npm create @sveltepress, the sidebar is open at all times and cant be closed in mobile view.
Same on firefox and chrome.

### Reproduction

After creating a project with npm create @sveltepress, the sidebar is open at all times and cant be closed in mobile view.
Same on firefox and chrome.

### Screenshots

```shell
https://gyazo.com/25d672fe9aa6d9d769025e9b416b301d
```

### Severity

blocking all usage of sveltepress

**Comment by appelskrutt34** [comment]
It sais in the console that .setCapture() is deprecated and .setPointerCapture() should be used instead.

**Comment by Blackman99** [comment]
Thanks for your feedback, I'll check this ASAP

**Comment by Blackman99** [comment]
Fixed in 3de34c5

**Comment by appelskrutt34** [comment]
Thank you!
