### ISSUE TITLE
Can't build quickstart project

### ISSUE THREAD

**Issue by appelskrutt34** [SveltePress/sveltepress#119]
### Describe the bug

Npm run build fails in quickstart project.

### Reproduction

run "npm create @sveltepress"
run npm install
run npm run build
Error message after running npm run build: Could not find file ".svelte-kit/generated/client-optimized/nodes/0.js" in Vite manifest

### Logs

```shell
Could not find file ".svelte-kit/generated/client-optimized/nodes/0.js" in Vite manifest
```

### Severity

blocking all usage of sveltepress

**Comment by Blackman99** [comment]
Thanks for your feedback!
I'm sorry I can not reproduce this problem. 
What version of Node.js are you using?

A reproduction link would be better

**Comment by appelskrutt34** [comment]
Im using the latest version of node 18.16.0

**Comment by Blackman99** [comment]
OK，I'll try to fix this ASAP

**Comment by Blackman99** [comment]
Looks like there's something wrong with the @sveltejs/kit package >= 1.15.11
Right now you can fix the @sveltejs/kit version to 1.15.10 to fix this

References:
https://github.com/sveltejs/kit/issues/9843
https://github.com/sveltejs/kit/issues/9811

**Comment by appelskrutt34** [comment]
I will try this. Thanks a lot :)

**Comment by Blackman99** [comment]
I'll watch the bug fix in sveltejs/kit repo.
I'll update the quick start template after the fix is done.

**Comment by Blackman99** [comment]
The release that contain fixes of this bug in sveltejs/kit repo has been released: https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%401.16.1

The release PR of this repo that contains upgrade both @sveltejs/kit and vite package to the latest version: #121
