### ISSUE TITLE
Customization of the features icons on home page

### ISSUE THREAD

**Issue by dsmtE** [SveltePress/sveltepress#129]
### Describe the problem

I want to be able to customize the set of icons used for the features of the default page (using a set iconify ideally, as this is well integrated using Unocss)

### Describe the proposed solution

I checked the code and documentation and from what I understand, for now, these icons come from custom svelte components from a predefined list in the home page script.

I suggest using _**"pure css icons"**_ instead, and passing in the theme options the list of icons we want to use, (within the constraint of having the necessary dependency in this case) or maybe the list of icon names we want to use, and maybe fallBack in some way on the built-in icon (like your svelte component to avoid the need for dependency on **_iconify-json/[the-collection-you-want]_** .

### Alternatives considered

Maybe another way of doing this is to just provide a list of svelte component to use (like you did) and let the used decide to use what he wants (icon from iconify, hard-coded svg in svelte components, etc...)

---

**PS:** I really like your project, it's an idea I've had in mind for a while (using svelte-kit to make a mardown site generator) but I haven't found or taken the time to do it and not being a web developer initially I would never be able to produce something so clean.

I would be happy to contribute to this nice project and implement this little feature (and others who knows) if you validate the direction (or if you have a better idea)

It's a real alternative(prod ready) to something like Docusaurus for me that deserves to be more widely known. 

### Importance

nice to have

**Comment by Blackman99** [comment]
Thanks for your feedback!

This is a very excellent suggestion. I'll work on this as soon as possible.

**Comment by dsmtE** [comment]
Would you like me to do it, via a PR?
How would you prefer it to be implemented?

**Comment by Blackman99** [comment]
And PR is welcome!

**Comment by dsmtE** [comment]
I'm sorry I won't be able to propose a PR soon, if you have time and an idea in mind, I'll let you do it.
I have other ideas for features request if you want.

**Comment by Blackman99** [comment]
Sure thing! I'll add this feature in the next release

**Comment by Blackman99** [comment]
This feature has been added in the latest release.
The relative docs: 
* https://sveltepress.site/guide/default-theme/home-page/#features
* https://sveltepress.site/reference/default-theme/#preBuildIconifyIcons
* https://sveltepress.site/guide/default-theme/builtin-components/#Icons-(Pre-build-iconify-icons)

**Comment by Blackman99** [comment]
I'm currently marking this issue as solved.
Re-open this if there are any further questions.
