### ISSUE TITLE
Mobile navigation improvements

### ISSUE THREAD

**Issue by theetrain** [SveltePress/sveltepress#140]
### Describe the problem

First off, I'm glad this project exists and I'm rooting for its long-term efforts.

The mobile navigator has too many interactions:

1. A top level nav
2. A side nav floating action button
3. An unlabelled floating button to toggle documentation nav
4. An unlabelled floating button to toggle 'on this page' nav

Annotated screenshot:
<img width="474" alt="image" src="https://github.com/SveltePress/sveltepress/assets/12798751/69cbf023-9c73-4630-9c7f-fa1e302e4a3e">

It's challenging to remember which button does what, and the floating action buttons hide content, especially when zooming in.

### Describe the proposed solution

1. Have a single hamburger menu; this will help avoid the re-learning curve on every site visit. Try to combine top-level navigation with documentation navigation.

Example from Docusaurus:

<img width="407" alt="image" src="https://github.com/SveltePress/sveltepress/assets/12798751/992af4f5-03b2-468a-adbb-44e1d87d7fb7">

2. It's okay to have 'on this page' nav be at the top of the page. It's usually not a lot of effort for users to scroll to the top of a page.

3. It would also be helpful to wrap the navigation area with `<nav aria-label="Menu">`

4. As a personal recommendation, do not make the top header sticky. You can consider auto-hiding it or keeping it statically placed at the top of the page. This avoids troublesome page shrink when zooming in or shrinking the window in a split-screen scenario.

### Alternatives considered

N/A

### Importance

i cannot use svelte without it

**Comment by Blackman99** [comment]
Thanks for your feedback!

This is really a good advice. Try to optimize it as soon as I can.

**Comment by Blackman99** [comment]
The Docusaurus's idea is not very good. Making "on this page section at the top " is unacceptable.
I took Vitepress as a reference to add a sub-nav on the bottom of the navbar.
And make the navbar auto hide/show when scrolling down/up

**Comment by theetrain** [comment]
The approach employed by VitePress involves a sticky header. I tested your new implementation; though it solves some problems, it introduces new issues:

1. The sticky navigation is always present even if the user zooms onto the page. Auto-hiding the top level nav is okay, and i recommend auto-hiding 'on this page' links along with it. Plus, it covers important headings when scrolled to the top of the page. 

   <img width="579" alt="image" src="https://github.com/SveltePress/sveltepress/assets/12798751/86451430-87e6-4934-ac86-2c84ff6aaf9c">

3. The docs sidenav and 'On this page' links are using `div` instead of `button`, which is necessary in order to be keyboard-accessible. Though you evaded compiler warnings with `on:keypress` ([commit reference](https://github.com/SveltePress/sveltepress/commit/72a54fd296042898d26ca89220bfe4c77398f975#diff-17f533f3c2a4d45c2a6b9caf827f69f7defc2fb0a60cef9d77e6daec51e16f19R16-R19)), it requires other attributes like `role` and `tabindex`. Using `button` covers all of these concerns.

4. The floating action button covers content. I don't recommend having them

   <img width="108" alt="image" src="https://github.com/SveltePress/sveltepress/assets/12798751/9f10ece6-de12-411c-927f-37a504dd771c">

5. There are now 2 hamburger menus that lack labelling, which inherits the same issues present in VitePress: it's unclear to the user which button opens top-level nav or documentation. I recommend adding visible labels such as "Menu" for top-level nav" and "Browse docs" for the documentation menu, or combine them into 1 navigation menu.

   <img width="127" alt="image" src="https://github.com/SveltePress/sveltepress/assets/12798751/07f8ce66-1f67-4c8b-8151-28cf0149ed83">

Some added reading: https://adamsilver.io/blog/the-problem-with-sticky-menus-that-appear-on-scroll-and-what-to-do-instead/

**Comment by Blackman99** [comment]
Thanks for your feedback!
These are very helpful suggestions.

Will fix these in the next release

**Comment by Blackman99** [comment]
Fix in #143
