### ISSUE TITLE
Light theme link contrast

### ISSUE THREAD

**Issue by theetrain** [SveltePress/sveltepress#141]
### Describe the bug

Navigation links in the light theme do not have sufficient contrast.

### Reproduction

Observe side navigation on desktop while viewing in the light theme.

Try aiming for higher contrast: https://webaim.org/resources/contrastchecker/

### Screenshots

<img width="280" alt="image" src="https://github.com/SveltePress/sveltepress/assets/12798751/e251f135-3afe-4691-be6e-4298439aa81f">

### Severity

annoyance

**Comment by Blackman99** [comment]
Thanks for your feedback!

Will fix this in the next release
