### ISSUE TITLE
SSR Build output null when using adapter-vercel

### ISSUE THREAD

**Issue by bitsquant** [SveltePress/sveltepress#145]
### Describe the bug

When running 'vite build' the buildoutput for .server.js files are empty.

### Reproduction

Heres my svelte.config.js
```
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';

/**
 * @type {import('@sveltejs/kit').Config}
 */
const config = {
	extensions: ['.svelte', '.md'],
	preprocess: [vitePreprocess()],
	kit: {
		adapter: adapter({
			pages: 'dist'
		})
	}
};

export default config;
```
When I run vite build the .server.js files are empty. FYI client side files are working perfectly

### Severity

annoyance

**Comment by Blackman99** [comment]
`adapter-auto` does not have any input parameters. 
And also you need to specify a adapter instead of `adapter-auto`, see here: https://kit.svelte.dev/docs/adapters

**Comment by Blackman99** [comment]
I've used `adapter-node` and it is working as expected.

**Comment by Blackman99** [comment]
Closing this for invalid. 
If there are any further questions. Feel free to open this again

**Comment by bitsquant** [comment]
@Blackman99 sorry my bad , I was not clear enough ..I did a little digging actually I am deploying my app on vercel with vercel-adapter. Which works by using adapter-vercel or adapter-auto. And if you check its generating empty .server.js files for page load functions.

**Comment by Blackman99** [comment]
Can you be more specific or provide a minimal reproduction link?

**Comment by bitsquant** [comment]
Hey, @Blackman99, I appreciate you reopening the issue. It appears that the problem lies with the adapter-vercel not handling shared config correctly(which svelte-press uses). You can find the issue and more details at this link: [GitHub Issue](https://github.com/sveltejs/kit/issues/10021).

To reproduce the issue, simply generate the build using adapter-vercel, and you'll notice empty +page.server.js files in the build output. However, if you switch to using adapter-node, +page.server.js is not empty.

**Comment by Blackman99** [comment]
Thanks for your efforts!
I'll check this and try to fix this

**Comment by Blackman99** [comment]
This is the page/layout RE is wrong. So @sveltepress/vite accidentally transform server files cause the result to be empty.

Fixed in: #150

**Comment by Blackman99** [comment]
Closing as completed

**Comment by bitsquant** [comment]
@Blackman99 Thank you very much! I've tested it, and now I'm successfully getting the output for .server.js files.

**Comment by kabootit** [comment]
@Blackman99 Thanks for your time on this! Saved our team and org a LOT of effort.

**Comment by danielcassiano** [comment]
Thank you, @Blackman99
