### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by jinhuan138** [SveltePress/sveltepress#156]
### Describe the bug

使用代码块报错

### Reproduction

ReferenceError: window is not defined

### Severity

annoyance

**Comment by Blackman99** [comment]
Did you use any third-party libraries?
Or can you provide more context, please?
Additionally, providing reproduction would be better.

**Comment by jinhuan138** [comment]
`
  onMount(() => {
    import("epubjs").then(model) => {
    
    });
  });
`
