### ISSUE TITLE
lastUpdate property return Invalid Date even though it's not invoked

### ISSUE THREAD

**Issue by slozano54** [SveltePress/sveltepress#162]
### Describe the bug

lastUpdate property return Invalid Date even though it's not invoked 

### Reproduction

First of all thank you for sharing your job,

The text "LastUpdate at : " is always rendered even though i dont use the property.

You can reproduce the problem with the code of this repo => https://github.com/slozano54/sveltepressTests
and temporarily in live => https://sandboxlaravel.webfac.fr/pv.html 

The code of the +page.md is : 

```
---
title: PetitVert
---
## some subtitle
some text
```

I can use the property but if i don't i would like the text "Last update at : ..." was not rendered, actualy i get "Last update at : Invalid Date" 

Curiously, it seems to be the expected behavior as i can see in your component  [here](https://github.com/SveltePress/sveltepress/blob/main/packages/theme-default/src/components/LastUpdate.svelte) 

![Sélection_770](https://github.com/SveltePress/sveltepress/assets/37615466/8ca79935-b93c-4ed3-80d8-04f4a1dc6dc9)

### Severity

annoyance

**Comment by Blackman99** [comment]
It is wirtten in the docs:
https://sveltepress.site/guide/default-theme/frontmatter/#lastUpdate

`lastUpdate` would auto use the git commit date of the +page file

If you don't want to use it. You can config `lastUpdate` frontmatter to `false`:

```md
---
title: Your title
lastUpdate: false
---
```

**Comment by slozano54** [comment]
Sorry about the noise !

The screenshot was online but infact the github url wasn't updated, I left "https://github.com/Blackman99/sveltepress" , so confused ! As soon as I changed the url in the vite.config.ts file, the date was rendered correctly.

Thanks and sorry for you wasted time

![Sélection_772](https://github.com/SveltePress/sveltepress/assets/37615466/8b1e1779-67cd-438d-87b5-a71f077a4917)
