### ISSUE TITLE
Sidebar Nested sub items

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [SveltePress/sveltepress#190]
### Describe the problem

To define a sidebar, you need to use this format:

```js
const sidebar = {
  '/foo/': [
    {
      title: 'Bar',
      to: '/foo/bar/',
    },
    // more items
  ]
}
```

To define a `sub-item`, you need to add an items property to the object. For example:

```js
    {
      title: 'Zoo',
      collapsible: true,
      items: [
        {
          title: 'Sub item',
          to: '/sub/item/link'
        }
      ]
    },
```

However, you cannot nest sub-items inside sub-items. In other words, you cannot have an `items` property inside another `items` property. For example, this is not allowed:

```js
    {
      title: 'Zoo',
      collapsible: true,
      items: [
        {
          title: 'Sub item',
          to: '/sub/item/link',
          items:[
            // more items
          ]
        }
      ]
    },
```

### Describe the proposed solution

A straightforward solution would be for SveltePress to support nested sidebar items.

### Alternatives considered

To support nested sidebar items, we can add an `id` and `parent` property to each item. This would allow us to filter which items are related to which other items.

For example, the following sidebar would be updated to include `id` and `parent` properties:

```js
const sidebar = {
  '/foo/': [
    {
      id: 'bar',
      title: 'Bar',
      to: '/foo/bar/',
      parent: null,
    },
    {
      id: 'zoo',
      title: 'Zoo',
      collapsible: true,
      parent: null,
    },
    {
      id: 'sub-item',
      title: 'Sub item',
      to: '/sub/item/link',
      parent: 'zoo',
    },
    {
      id: 'sub-sub-item',
      title: 'Sub sub item',
      to: '/sub/sub/item/link',
      parent: 'sub-item',
    },
    {
      id: 'external-github-page',
      title: 'External github page',
      to: 'https://github.com',
      parent: null,
    },
  ],
};
```
With these properties, we can easily filter which items are related to which other items.

### Importance

would make my life easier

**Comment by Blackman99** [comment]
Thanks for your feedback!
The nested sidebar is being considered as a feature in the next release. It requires a little bit long time to ensure the compatibility with current UI. Thanks for your patience.

**Comment by Blackman99** [comment]
#196
