### ISSUE TITLE
Can't use TypeScript in *.svelte files

### ISSUE THREAD

**Issue by a-kla** [SveltePress/sveltepress#191]
### Describe the bug

If I add Typescript to a *.md* file like:

```svelte
<script lang="ts"> //  +` lang="ts"` for TypeScript
  let count:number = 0 // + `:number`
</script>

<button on:click="{() => count++}">
  You've clicked {count} times
</button>
```
It works as expected.

If I use **the same Code** in a *+page.svelte* file I get a 404 or 500 Error Page.
(log see below)

If I remove ` lang="ts"` from the Script my IDE shows the errors and a Hint:

> Unexpected token
> 
> If you expect this syntax to work, here are some suggestions: 
> If you use typescript with `svelte-preprocess`, did you add `lang="ts"` to your `script` tag? 
> Did you setup a `svelte.config.js`? 
> See https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors for more info.svelte(parse-error)

This means Typescript is interpreted as JavaScript in *.svelte files.

### Reproduction

run `pnpm create @sveltepress` and chose Typescript as Language.

Then create a *.svelte file with Typescript. 

### Logs

```shell
Internal server error: Unexpected token
  Plugin: @sveltepress/vite
  File: […]/src/routes/tests/+page.svelte:2:12
  1: <script lang="ts">
  2:   let count:number = 0
                ^
  3: </script>
 […]
```

### Severity

blocking an upgrade

**Comment by Blackman99** [comment]
Thanks for your feedback!
Will fix this in the next release. Thanks for your patience!

**Comment by a-kla** [comment]
Thanks.
There is no need to hurry up. Need time for my App anyway.

I use MDsevX right now.
It didn't break my app and works like Sveltepress without Theme.
But i like to use your Theme and MDsevX seams to be [incompatible to remark-directive](https://github.com/pngwn/MDsveX/issues/533).

**Comment by Blackman99** [comment]
#182
