### ISSUE TITLE
`@sveltepress/theme-default@1.20.0` breaks layout

### ISSUE THREAD

**Issue by TorstenDittmann** [SveltePress/sveltepress#193]
### Describe the bug

Looks like with `@sveltepress/theme-default@1.20.0` the sidebar is always visible and cannot be closed. Therefore block a big chunk of the screen.

### Reproduction

Visit https://sveltepress.site/

### Screenshots

https://github.com/SveltePress/sveltepress/assets/1759475/a80978e7-ebcc-4c58-a3b9-f9a1052c7596

### Severity

blocking an upgrade

**Comment by Blackman99** [comment]
Thanks for your feedback!
Fix here: #194
