### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by elucian** [SveltePress/sveltepress#216]
### Describe the bug

To install, I have run in empty folder: 
sudo npm install -g @sveltepress/create
But documentation say to run 
npm create @sveltepress
Maybe documentation need update? 

### Reproduction

https://sveltepress.site/guide/quick-start/

### Severity

annoyance

**Comment by Blackman99** [comment]
Thanks for the feedback!
There's somthing wrong with the `@sveltepress/create` package. Will fix it in the next release
