### ISSUE TITLE
Allow to export to PDF

### ISSUE THREAD

**Issue by gevera** [SveltePress/sveltepress#220]
### Describe the problem

There is no straightforward option to export all the website with its pages as a PDF book

### Describe the proposed solution

A "npm run pdf-export" command or a button somewhere to execute the command 

### Alternatives considered

Print from the browser

### Importance

nice to have

**Comment by riziles** [comment]
I've been working on using [MyST](https://mystmd.org/) to render the Markdown directly to PDF. There are some tricky differences in syntax, but the output is beautiful. If you have custom components in your Markdown, you have to use Playwright or Puppeteer to export those to images.

**Comment by Blackman99** [comment]
Thanks for your feedback!
I'm afriad this won't be considered as a built-in feature. As @riziles mentioned above, sveltepress has many customize svelte components. Which means you can't transfer them to PDF directly util all the whole page is rendered by Browser. 
I think you can search for some browser extensions that may meet your need.
