### ISSUE TITLE
themeColor after SRR

### ISSUE THREAD

**Issue by jycouet** [SveltePress/sveltepress#226]
### Describe the bug

It looks like `defaultTheme` is set and working during SSR with my settings, but just after, it's replaced to default.

I'm I missing something?
Thx for your help

### Reproduction

https://github.com/SveltePress/sveltepress/assets/5312607/912ce155-9799-42e5-82cd-e9bf0935220d

### Severity

annoyance

**Comment by Blackman99** [comment]
Thanks for your feedback!
I need to check for more details. Hopefully this would be fixed in the next release

**Comment by Blackman99** [comment]
Can you clear your cache can try again? I can not reproduce this in my computer.
It it more convenient that you can provice a reproduction link, thanks!

**Comment by jycouet** [comment]
👋 hi there, 
Sorry that I didn't came back earlier... I wanted to do a repro RN, but I can't reproduce it in the place where I did the video! :o

Maybe something cached somewhere? 
nvm, I'll close 👍, and will use it ;)
