### ISSUE TITLE
SvelteKitError: Not found: /.https://github.com/Blackman99/sveltepress

### ISSUE THREAD

**Issue by tukusejssirs** [SveltePress/sveltepress#233]
### Describe the bug

When building the example website, I get the following error: `SvelteKitError: Not found: /.https://github.com/Blackman99/sveltepress`.

For some reason, an external URL seems to be considered an internal path, although it is explicitly configured as external:

https://github.com/SveltePress/sveltepress/blob/80960f09320e57a536536dbba8868bdb76603c88/packages/create/template-js/src/routes/%2Bpage.md?plain=1#L6-L9

Note that it works when running `pnpm dev`, but does not work with `pnpm build` (see the [repoduction](#reproduction)).

Also note that you seem to have renamed the repo org name to `SveltePress`, therefore, consider changing `https://github.com/Blackman99/sveltepress` to `https://github.com/SveltePress/sveltepress`.

### <a name='reproduction'></a>Reproduction

```bash
echo -e '\n' | pnpm create @sveltepress docs
cd docs
pnpm i
pnpm build
```

### Logs

```shell
SvelteKitError: Not found: /.https://github.com/Blackman99/sveltepress
    at resolve2 (file://$docs_root/.svelte-kit/output/server/index.js:3604:18)
    at resolve (file://$docs_root/.svelte-kit/output/server/index.js:3436:34)
    at #options.hooks.handle (file://$docs_root/.svelte-kit/output/server/index.js:3679:71)
    at respond (file://$docs_root/.svelte-kit/output/server/index.js:3434:43) {
  status: 404,
  text: 'Not Found'
}

node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^
Error: 404 /.https://github.com/Blackman99/sveltepress (linked from /)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file://$docs_root/node_modules/.pnpm/@sveltejs+kit@2.5.1_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.4/node_modules/@sveltejs/kit/src/core/config/options.js:202:13
    at file://$docs_root/node_modules/.pnpm/@sveltejs+kit@2.5.1_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.4/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:65:25
    at save (file://$docs_root/node_modules/.pnpm/@sveltejs+kit@2.5.1_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.4/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file://$docs_root/node_modules/.pnpm/@sveltejs+kit@2.5.1_@sveltejs+vite-plugin-svelte@3.0.2_svelte@4.2.12_vite@5.1.4/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)

Node.js v21.6.2
 ELIFECYCLE  Command failed with exit code 1.
```

### Severity

annoyance

### Versions

- `pnpm@8.15.3`;
- `node@21.6.2`;
- `npm@10.2.4`.

```bash
# jq .devDependencies package.json 
{
  "@sveltejs/adapter-static": "^3.0.1",
  "@sveltejs/kit": "^2.0.6",
  "@sveltepress/theme-default": "^1.22.6",
  "@sveltepress/vite": "^0.31.6",
  "@types/node": "^20.10.6",
  "svelte": "^4.2.8",
  "typescript": "^5.3.3",
  "vite": "^5.0.10",
  "@sveltejs/vite-plugin-svelte": "^3.0.1"
}
```

**Comment by Blackman99** [comment]
Thanks for your feedback!
Are you using the latest code? I can successfully build the docs site in the latest main branch

**Comment by tukusejssirs** [comment]
Well, I have installed it using `pnpm create @sveltepress`, as per the [docs](https://sveltepress.site/guide/quick-start/#Creating-a-project), therefore, I presume, yes. Seed the bottom of the OP for the versions I used and `pnpm create @sveltepress` has installed.

**Comment by tukusejssirs** [comment]
BTW, it also happens when I use `pnpm create @sveltpress@latest` which installs the following deps:

```js
// jq .devDependencies package.json 
{
  "@sveltejs/adapter-static": "^3.0.1",
  "@sveltejs/kit": "^2.0.6",
  "@sveltepress/theme-default": "^1.22.6",
  "@sveltepress/vite": "^0.31.6",
  "@types/node": "^20.10.6",
  "svelte": "^4.2.8",
  "typescript": "^5.3.3",
  "vite": "^5.0.10",
  "@sveltejs/vite-plugin-svelte": "^3.0.1"
}
```

**Comment by tukusejssirs** [comment]
It’s all in the OP:

```bash
echo -e '\n' | pnpm create @sveltepress docs
cd docs
pnpm i
pnpm build
```

**Comment by tukusejssirs** [comment]
And it also happens with `npm`.

**Comment by Blackman99** [comment]
There's something wrong with the ActionButton component in @sveltepress/theme-default package. Will fix it in the next release. 
Thanks for your help!
