### ISSUE TITLE
Access current light/dark mode state via context store

### ISSUE THREAD

**Issue by gka** [SveltePress/sveltepress#243]
### Describe the problem

For some of the examples in my SveltePress page I would love to know if the page is currently in dark or light mode.

### Describe the proposed solution

it would be great if from my Svelte pages and live components I could just access a global `isDark` store, perhaps like this

```js
import { getContext } from 'svelte';
const { isDark } = getContext('sveltepress');
```

### Alternatives considered

The alternative would be to somehow track if there's a `.dark` class set on the `<html>` element, which doesn't really work reactively without a lot of hazzle. 

### Importance

nice to have

**Comment by Blackman99** [comment]
New docs: https://sveltepress.site/reference/default-theme/#Global-context
