### ISSUE TITLE
Development mode does not work: Theme does not update and links are broken

### ISSUE THREAD

**Issue by reednaa** [SveltePress/sveltepress#262]
### Describe the bug

Developer mode is broken: Link do not load on first try (HMR update fails).

I am not sure if related but it is also not possible to set custom themes on a fresh installation. Instead the custom theme flashes and then the default theme appears.

### Reproduction

```
git clone https://github.com/SveltePress/sveltepress.git
cd sveltepress/packages/docs-site/
pnpm install
pnpm dev
```

Go to website. Any first click on an unclicked link results in a crash.

### Severity

blocking all usage of sveltepress

**Comment by Blackman99** [comment]
Please make sure you are not using safari or IE browser and provide your environment information: node version, pnpm version, browser version

**Comment by reednaa** [comment]
Why doesn't Safari work?

**Comment by Blackman99** [comment]
Safari is basically the next IE.
