### ISSUE TITLE
Invalid CSS when building

### ISSUE THREAD

**Issue by avocolado** [SveltePress/sveltepress#268]
### Describe the bug

When developing everything appears as per the documentation. However when building and previewing the CSS will no longer apply.

Development
<img width="1040" alt="Dev" src="https://github.com/SveltePress/sveltepress/assets/161639371/65c0211e-6744-4eae-9c21-a50777dc30a6">

After building
<img width="1043" alt="Build" src="https://github.com/SveltePress/sveltepress/assets/161639371/ab561032-1d2e-48cb-afc9-9dfb7e6abe3d">

### Reproduction

```
npm create @sveltepress
# create demo
cd demo
npm run dev
```
Create a subroute with `+page.md` and give it a title and text like the following:

```
---
title: Demo Test
---

Is this working? Placeholder text to extend the text past the initial sidebar and confirm that it is indeed appearing.
```

```
npm run build && vite preview
```

You should see that the CSS no longer applies. Tested on Firefox and Chrome.

### Severity

blocking all usage of sveltepress

**Comment by Blackman99** [comment]
Thanks for your feedback!
Can confirm this exists and has something to do with the sveltekit build match unocss. Will fix this in the next release.
