### ISSUE TITLE
Adding large images breaks bounding box

### ISSUE THREAD

**Issue by avocolado** [SveltePress/sveltepress#270]
### Describe the bug

Adding large images will cause the images to break out of the container on documentation pages

### Reproduction

Add a large image to a `+page.md` and it will break out of its container and spill over onto the right.
<img width="1072" alt="Screenshot 2024-04-29 at 2 16 27 PM" src="https://github.com/SveltePress/sveltepress/assets/161639371/19a3b480-e08c-435d-a77f-3181cba19ead">

### Severity

blocking an upgrade

**Comment by Blackman99** [comment]
Thanks for your feedback!
Will add style restriction for default img in the next release.
You can also add custom styles for your image too.
