### ISSUE TITLE
Too many shiki instances

### ISSUE THREAD

**Issue by jycouet** [SveltePress/sveltepress#285]
### Describe the bug

I started to add some codeblocs on my doc, and I get in `dev` a lot of
![image](https://github.com/user-attachments/assets/358fb3c0-5eed-42dd-a938-caab56b7a9a3)
(not knowing from where it could come from.)

I decided to do a build, and here I have this message: 
```bash
10 instances have been created. 
Shiki is supposed to be used as a singleton, 
consider refactoring your code to cache your highlighter instance; 
Or call `highlighter.dispose()` to release unused instances.
```

So I think that it could be something on your side ? 

I'm using: 
```
"@sveltepress/theme-default": "3.0.0",
"@sveltepress/vite": "0.34.0",
```

### Reproduction

https://github.com/jycouet/firstly/tree/doc-improvements/docs

### Severity

blocking all usage of sveltepress

**Comment by Blackman99** [comment]
Thanks for your feedback, will fix this in the next release

**Comment by Blackman99** [comment]
Can you show the version of @sveltepress/theme-default please?
If it is under 3.0.0. You can update to 3.0.0 and try agian

**Comment by Blackman99** [comment]
Sorry for that

I went through the reporduction link. And tried `dev` adn `build`. But can not reproduce this. 
Would you mind provide more use context?
* OS type and version info
* Node verison
* Other usage senarios that might help

**Comment by Blackman99** [comment]
#286

**Comment by jycouet** [comment]
I'm on Ubuntu 22.04 (with WSL)
node v22.6.0
Using `pnpm`

I just cloned it again, and I don't mange to reproduce it in dev 🤔

But `npm build` (in docs folder) gives me the warning: 
```ts
vite v5.4.1 building SSR bundle for production...
transforming (1) ../node_modules/.pnpm/@sveltejs+kit@2.5.24_@sveltejs+vite-plugin-svelte@3.1.2_svelte@4.2.18_vite@5.4.1_@types+node@_lnml5jet[Shiki] 
10 instances have been created. 
Shiki is supposed to be used as a singleton, consider refactoring your code to cache your highlighter instance; 
Or call `highlighter.dispose()` to release unused instances.
```

Maybe a bump of deps would help... I don't know. 
If you release `exp` or `next` version, I can check it out

**Comment by Blackman99** [comment]
The new release has been published. Would you mind try it and see if it's fixed?

**Comment by jycouet** [comment]
Just tested it and yeah, it look like it's fixed, thank you 👍
