### ISSUE TITLE
Upgrade to Svelte 5

### ISSUE THREAD

**Issue by benmccann** [SveltePress/sveltepress#291]
### Describe the problem

The new project creating template uses Svelte 4: https://github.com/SveltePress/sveltepress/blob/a85c9cd4eeab326547b42123e9ba2214377c7260/packages/create/template-ts/package.json#L18

It would be nice for new projects to use Svelte 5

### Describe the proposed solution

Update the versions in `package.json` and move from slot to snippet. `sv migrate svelte-5` would probably do it for you

### Alternatives considered

n/a

### Importance

would make my life easier

**Comment by Blackman99** [comment]
Thanks for your feedback.
Will update ASAP

**Comment by Blackman99** [comment]
#292

**Comment by benmccann** [comment]
amazing! thank you!!
