### ISSUE TITLE
Cant create a new project (Error: ENOENT: no such file or directory)

### ISSUE THREAD

**Issue by Lettuce144** [SveltePress/sveltepress#299]
### Describe the bug

When trying to create a new SveltePress project an error appears that says that the default template isn't found.

### Screenshot
![afbeelding](https://github.com/user-attachments/assets/4f75d691-b55a-453a-b99f-43b6e7f33372)

### Reproduction

npm create @sveltepress 

Javascript >
(choosing typescript gives this error too)

### Logs

```shell
Scaffolding project in /home/jens/Documenten/ProjectsLocal/sveltepress-project...
Error: ENOENT: no such file or directory, scandir '/home/jens/.npm/_npx/ca86dd19ffbc033f/node_modules/@sveltepress/create/template-js'
    at Object.readdirSync (node:fs:1502:26)
    at init (file:///home/jens/.npm/_npx/ca86dd19ffbc033f/node_modules/@sveltepress/create/dist/index.mjs:138:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/jens/.npm/_npx/ca86dd19ffbc033f/node_modules/@sveltepress/create/template-js'
}
```

### Severity

blocking all usage of sveltepress

**Comment by Blackman99** [comment]
Thanks for your feedback!
A new version of @sveltepress/create (1.1.1) package was published to fix this.

Use `npm create @sveltepress@lastest` to check it.
