### ISSUE TITLE
ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @shikijs/twoslash@catalog: isn't supported by any available resolver.

### ISSUE THREAD

**Issue by davay** [SveltePress/sveltepress#300]
### Describe the bug

I had just tried the fix for #299 and it did work to create a new project. However,  when doing `pnpm install` I'm getting this error:

```
ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @shikijs/twoslash@catalog: isn't supported by any available resolver.

This error happened while installing the dependencies of @sveltepress/theme-default@5.0.0
 at @sveltepress/twoslash@1.1.0
 ```
 
Perhaps from #298? 

A similar issue also occurs with npm 

```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "catalog:": catalog:
```

### Reproduction

`pnpm create @sveltepress@latest` then `pnpm install`

OR

`npm create @sveltepress@latest` then `npm install`

### Severity

blocking all usage of sveltepress

**Comment by Blackman99** [comment]
Thanks for your feedback!
New version of @sveltepress/create (1.1.2) and @sveltepress/theme-default (5.0.1)
were published to fix this.

If your project has already been created. You can udpate  @sveltepress/theme-default to 5.0.1 to solve this.

Can also you can create a new project by running `pnpm create @sveltepress@latest`

**Comment by davay** [comment]
Thank you for your continuous effort, sveltepress is properly running locally now from a fresh create 👍

**Comment by gka** [comment]
FYI, updating to @sveltepress/theme-default to 5.0.4 didn't fix this for me.

```
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @shikijs/twoslash@catalog: isn't supported by any available resolver.

This error happened while installing the dependencies of @sveltepress/theme-default@5.0.4
 at @sveltepress/twoslash@1.1.3

An external package outside of the pnpm workspace declared a dependency using
the catalog protocol. This is likely a bug in that external package. Only
packages within the pnpm workspace may use catalogs. Usages of the catalog
protocol are replaced with real specifiers on 'pnpm publish'.

This is likely a bug in the publishing automation of this package. Consider filing
a bug with the authors of:

  @sveltepress/theme-default@5.0.4

Progress: resolved 233, reused 211, downloaded 18, added 0
```

**Comment by gka** [comment]
Looking at the error message this bug doesn't seem to originate from `@sveltepress/theme-default` but from `@sveltepress/twoslash`. More precesily `pnpm` doesn't seem to tolerate these `catalog:` dependencies:

https://github.com/SveltePress/sveltepress/blob/959d7fbd58228adb1f9105b20862bd5c74f5380a/packages/twoslash/package.json#L41-L42

@Blackman99 should I open a new ticket for this or do you want to reopen this one?

**Comment by gka** [comment]
I just tested this with a fresh sveltepress project and I get the same error message:

```bash
$ node --version
v22.5.1
$ pnpm --version
9.15.0
$ pnpm create @sveltepress@latest
✔ Project name: … sveltepress-project
✔ Use Javascript or Typescript for your new project? › Typescript

Scaffolding project in /Users/gregor.aisch/projects/test/sveltepress-project...

Done. Now run:

  cd sveltepress-project
  pnpm install
  pnpm run dev

$ cd sveltepress-project
$ pnpm i
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @shikijs/twoslash@catalog: isn't supported by any available resolver.

This error happened while installing the dependencies of @sveltepress/theme-default@5.0.4
 at @sveltepress/twoslash@1.1.3

An external package outside of the pnpm workspace declared a dependency using
the catalog protocol. This is likely a bug in that external package. Only
packages within the pnpm workspace may use catalogs. Usages of the catalog
protocol are replaced with real specifiers on 'pnpm publish'.

This is likely a bug in the publishing automation of this package. Consider filing
a bug with the authors of:

  @sveltepress/theme-default@5.0.4

Progress: resolved 142, reused 106, downloaded 4, added 0
```
