### ISSUE TITLE
Can't install a fresh Sveltepress instance with pnpm due to catalog import

### ISSUE THREAD

**Issue by gka** [SveltePress/sveltepress#305]
### Describe the bug

Same issue as https://github.com/SveltePress/sveltepress/issues/300, but it still exists so I'm opening a new ticket. When installing the latest Sveltepress with pnpm, the install fails with the following message:

`ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @shikijs/twoslash@catalog: isn't supported by any available resolver.`

In #300 it was suggested, that updating `theme-default` would fix this. However, the bug doesn't seem to originate from `@sveltepress/theme-default` but from `@sveltepress/twoslash`. More precisely `pnpm` doesn't seem to tolerate these `catalog:` dependencies:

https://github.com/SveltePress/sveltepress/blob/959d7fbd58228adb1f9105b20862bd5c74f5380a/packages/twoslash/package.json#L41-L42

### Reproduction

I just tested this with a fresh sveltepress project and I get the same error message:

```bash
$ node --version
v22.5.1
$ pnpm --version
9.15.0
$ pnpm create @sveltepress@latest
✔ Project name: … sveltepress-project
✔ Use Javascript or Typescript for your new project? › Typescript

Scaffolding project in /Users/gregor.aisch/projects/test/sveltepress-project...

Done. Now run:

  cd sveltepress-project
  pnpm install
  pnpm run dev

$ cd sveltepress-project
$ pnpm i
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @shikijs/twoslash@catalog: isn't supported by any available resolver.

This error happened while installing the dependencies of @sveltepress/theme-default@5.0.4
 at @sveltepress/twoslash@1.1.3

An external package outside of the pnpm workspace declared a dependency using
the catalog protocol. This is likely a bug in that external package. Only
packages within the pnpm workspace may use catalogs. Usages of the catalog
protocol are replaced with real specifiers on 'pnpm publish'.

This is likely a bug in the publishing automation of this package. Consider filing
a bug with the authors of:

  @sveltepress/theme-default@5.0.4

Progress: resolved 142, reused 106, downloaded 4, added 0
```

### Severity

blocking an upgrade

**Comment by Blackman99** [comment]
#306
