### ISSUE TITLE
Search in Navbar

### ISSUE THREAD

**Issue by gevera** [SveltePress/sveltepress#76]
### Describe the problem

It would be great to have a out of the box Search module, just like in VuePress.
Search for routes, frontmatter and headings.

### Describe the proposed solution

Add a plugin in svelteConfig like so

```JS
plugins: [
    ['@sveltepress/search', {
      searchMaxSuggestions: 10
    }]
  ]
```

### Alternatives considered

Maybe as an alternative, an Algolia provider. It would be better to have a solution without any third parties though

### Importance

would make my life easier

**Comment by Blackman99** [comment]
Algolia search can be configured by provide `docsearch` option to default theme, you can read about It here:

https://sveltepress.site/reference/default-theme/#docsearch

**Comment by Blackman99** [comment]
The docsearch chapter has been added to the docs site:
https://sveltepress.site/guide/default-theme/docsearch/

Close this issue for resolved.
