### ISSUE TITLE
Sidebar configuration

### ISSUE THREAD

**Issue by gevera** [SveltePress/sveltepress#77]
### Describe the problem

It would be great to have a possibility to control the sidebar from the config file

### Describe the proposed solution

In svelte config or some specific config file for sveltepress to add something like so

```js
 sidebar: [
      '/',
      '/page-a',
      ['/page-b', 'Explicit link text']
    ]
```

### Alternatives considered

N/A

### Importance

would make my life easier

**Comment by Blackman99** [comment]
You can find provide `sidebar` config to theme default to customize sidebar

You can read about it here:
https://sveltepress.site/reference/default-theme/#sidebar

I'll consider add a section in guide. It would make it easier for beginners

**Comment by Blackman99** [comment]
The sidebar section has been added to docs site:

https://sveltepress.site/guide/default-theme/sidebar/

Close this issue by resolved
